### ISSUE TITLE
Applying resample on interleaved signals

### ISSUE THREAD

**Issue by Bert-Proesmans** [jthiem/nnresample#4]
Hi,

Currently i have stereo interleaved audio signals which i want to upsample from 44.1KHz into 48KHz. The purpose would be to upsample audio for each incoming 20ms audio frame (~ real-time).

Is there a clever way how i can use this library to process both signals at the same time? I guess separating both signals into 2 buffers and then merging them after is a possibility, but that introduces a considerable amount of delay which i'd prefer to avoid.

Thank you in advance.

**Comment by jthiem** [comment]
Hi, yes it is possible.  The scipy.resample_poly function takes an "axis" argument; you can pass an ND array to it and it will resample every row or column of the supplied array.

If you have interleaved data from your A/D converter, the trick is to just use numpy.reshape in a clever way to get your data properly into two rows or columns:

>> a = np.array([1, 11, 2, 12, 3, 13])
>> print(np.reshape(a,(3,2)))
[[ 1 11]
 [ 2 12]
 [ 3 13]]

Now you can call resample_poly with argument axis=0 and it will resample along the columns. (please verify, I'm typing this without easy double-checking - it could be axis=1)

There are however some other issues if you're trying to do real-time resampling. (None fatal, but must be addressed).

1. resample_poly has no way of saving the antialiasing filter state.  Not really a problem since it's a FIR filter, you just need to add part of the previous frame to the current frame and trim the resampled frame appropiately.  Working out exactly how much to add is a bit fiddly, since it depends on the filter order, but can be done.  I'll try to get around writing some demo code.

2. Python (for all its nice qualities) is generally not a good language for real-time processing, due to the GIL and GC.  Generally not an issue on modern fast machines but could be problematic on computers with limited resources (eg, a Raspberry Pi)

Issue 1 and the deinterleaving are relatively easy to solve, but issue 2 simply comes down to using C instead of using Python.  If you like nnresample due to its antialiasing filter (which is its raison d'être) you can use nnresample to generate the filter, export it, and then use it with the C-library of your choice (eg. libtsp (function FIfConvSI), or the Secret Rabbit Code library).

Hope this helps!

**Comment by Bert-Proesmans** [comment]
Hi, thanks for your answer.
In the meantime i experimented with numpy and got interleaving and deinterleaving figured out.

First of all i'm gonna admit that it know little to nothing about audio/signal processing. I only recently started my hobby project and am learning a lot as i go. It could be that the things i'll try to explain sound dumb or are plain incorrect.
I actually started out by writing a (my first, yay!) c-extension for python wrapping the [Opus tools' resampler](https://github.com/xiph/opus-tools/blob/bd65450d9192673208f6e6caf8da1482277c2df4/src/resample.c). It kinda worked but couldn't figure out how to properly use it or tweak it if need be. 
So i went back to python and found this library. Python is easier for quick experimentations..
So far i have experimented with the nyquist and kaiser filters and generally the output sounds great. 
Fast Kaiser sounds ok (resampy), but high quality Kaiser sounds terrible. I can't understand why.
NyQuist sounds great as well. One thing i noted though; the low frequencies (some bass steps in the beat) get exagerated to the point that it sounds like cracking speakers. The song i'm testing on is this one: https://open.spotify.com/track/1rFAG22RkvaM6BlpWQoZ47. (I'm aware that parts of the song sound noisy, especially the intro)

I did not know about the two libraries you mentioned and will check them out. In the end it's quite possible i will turn to C or Rust for the resampling procedure.. when i have a better idea about what i'm exactly doing.

**Comment by jthiem** [comment]
From a quick look the opus tools resampler looks OK from an implementation standpoint - it appears to handle the state of the filter for block-based processing.  However, it states up front that it's not the best in terms of SNR and the perceptual arguments seem suspect to me... the argument is made so that far shorter filters can be used.  I am a fan of long filters to give high quality.  Processing is cheap and the delays aren't that big.

Anyways, I'll work out (eventually) how to do buffering with memory in python.  That should translate well into C or Rust in the end.  Can I ask what the application will be?

**Comment by Bert-Proesmans** [comment]
I'm building a Discord bot (for fun) and wanted it to play music from Spotify in a voice channel. 
As spotify client i'm using "librespot" which is wrapped in a python extension (for control, but it's also possible to control the player through other spotify apps) and audio is written to a python buffer object. For interaction with discord i use "discord.py".
Audio output sent to the sink is dual channel i16/44.1KHz pcm data, but for the voice system (including opus encoder) to work i need to feed it 20ms stereo audio in pcm at i16/48KHz or 'some opus encoded data'. 
Since opus only really works with 48KHz samples i went for the upsampling approach. For the PoC i intended to have the systems separated communicating through python. Later i could push the entire pipeline [PCM -> OPUS] into an extension for librespot to minimize delay and buffer copies.

Edit: You can find the forks i made on my profile. I made the resample wrapper extension private because i accidentally pushed private information in the test files.

**Comment by jthiem** [comment]
Sounds neat, I wish you success. I'll keep an eye on it!
